🐛 Fixed 404 routing in API
TryGhost/Ghost pull request #10070
Opened 2018-10-26 12:09 UTC by anaplian

closes #10020

I added a default API application that always returns a 404 error response. This is so that requests that don't get routed to any particular API are given a properly JSON-formatted 404 error (previously they were routed to the admin app's 404 page.)

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `npm test`)

2018-10-26 12:11 UTC, kirrg001 commented
Thanks will review on Monday :)

2018-10-27 17:25 UTC, kirrg001 requested changes
Thanks for your PR. I've left a comment :)

2018-11-06 11:49 UTC, kirrg001 commented
@anaplian ping :)

2018-11-07 22:51 UTC, anaplian commented
Thanks for the feedback :slightly_smiling_face: 
Working on it now!

2018-11-12 21:04 UTC, kirrg001 commented on core/server/web/api/index.js
> +    apiApp.use(urlUtils.getVersionPath({version: 'v2', type: 'admin'}), require('./v2/admin/app')());
The PR looks great 👍 
Was wondering why we mount urls without trailing slash now? 🤔

2018-11-15 11:33 UTC, kirrg001 commented on core/server/web/api/index.js
> +    apiApp.use(urlUtils.getVersionPath({version: 'v2', type: 'admin'}), require('./v2/admin/app')());
Was resolved in an extra commit 👍

2018-11-15 11:34 UTC, kirrg001 commented
@allouis Could you pls double check/test this PR on Monday? I think this one is good to go 👍

2018-11-15 11:34 UTC, kirrg001 approved these changes

2018-11-19 22:09 UTC, gargol commented
@allouis lmk if we can merge this PR in for tomorrow's release :wink:

2018-11-26 09:35 UTC, merged