Update documentation URLs
TryGhost/Ghost pull request #10150
Opened 2018-11-12 18:38 UTC by korigod

https://docs.ghost.org/docs page is no longer available so the link leads to 404 error. Other links were updated where appropriate too.

I'm not sure about `https://docs.ghost.org/docs/upgrade` link which leads now to question about specific version (https://docs.ghost.org/faq/upgrade-to-ghost-2-0) so I left it as it is.

2018-11-12 19:26 UTC, kirrg001 requested changes
Thanks for your PR 👍

2018-11-12 19:42 UTC, korigod commented on README.md
> +or on a server run the full install, including automatic SSL setup using LetsEncrypt - [Production install docs](https://docs.ghost.org/install/ubuntu/)
But `/setup` is not "Production install docs", it's all install docs. In this case we should adjust the description too.

2018-11-12 19:47 UTC, korigod commented
@kirrg001, thanks for your review, the commit has been amended.

2018-11-12 21:00 UTC, kirrg001 commented on README.md
> +or on a server run the full install, including automatic SSL setup using LetsEncrypt - [Production install docs](https://docs.ghost.org/install/ubuntu/)
Will come back to you tomorrow 👍

2018-11-13 07:36 UTC, kirrg001 commented on README.md
> +or on a server run the full install, including automatic SSL setup using LetsEncrypt - [Production install docs](https://docs.ghost.org/install/ubuntu/)
Ok we keep it like that 👍

2018-11-13 07:38 UTC, kirrg001 approved these changes

2018-11-13 07:38 UTC, merged