Destroyed user sessions when changing password
TryGhost/Ghost pull request #10872
Opened 2019-07-04 13:07 UTC by vikaspotluri123

- includes refactoring to use modern js features

closes #10323 

I've done what I'm relatively confident in for now, but there are a things:

- Ghost Admin doesn't work because all requests 403 - this might be bug that needs to be addressed, or an edge case that needs to be handled. Currently, getting a 403 is pretty much the same UX as getting a 404.
  - This could be prevented by not signing the user out, but I'm not entirely sure how I would go about doing this... my first thought is adding the current session_id to the changePassword model call in the API microframework layer, but I'm not entirely sure how to do that, or if it's realistic.

- No tests... I'm not exactly sure where to add them 🌵

2019-07-05 14:27 UTC, gargol commented
@vikaspotluri123 think we don't have to merge https://github.com/TryGhost/eslint-plugin-ghost/pull/12 in order for async/await syntax to start working as it already does in master after merging in `eslint` bump to `6.0.1` (https://github.com/TryGhost/Ghost/commit/db53ac072109b62f02309421742c76f8cbeda85c) which also dropped Node v6 support (https://eslint.org/docs/user-guide/migrating-to-6.0.0#-nodejs-6-is-no-longer-supported). 

Tried `yarn lint` on your branch and it passed just fine, all you have to do is rebase over master :wink:

2019-07-05 14:55 UTC, gargol commented
Ignore the above. Gotten the eslint-plugin-ghost linked and forgot to turn it off when experimenting with the change. It confirms the contrary, the PR you've opened for eslint-plugin-ghost works and should be merged first :grimacing:

2019-07-05 15:37 UTC, gargol commented
The new version of `eslint-plugin-ghost` is in master :tada: async/await linting should pass now.

2019-07-05 15:48 UTC, gargol commented
It's :green_book: Yew!

2019-07-08 13:08 UTC, gargol commented
@vikaspotluri123 the changes look good, but we'd need to clarify the flow before moving on :smiley: Have added a comment in the original issue and once we come to the conclusion that solution can be implemented :+1: 

The things you've mentioned that are not working in Ghost Admin after the password reset are linked to the decision we make on session management. In case we keep the current session alive (which I think is sensible) there won't be any 403s to deal with, as you correctly mentioned already :wink: 	

As for tests. Think this is a rarely touched area and a rather specific scenario to test, so the test itself can go into "regressions" [user suite](https://github.com/TryGhost/Ghost/blob/2.25.0/core/test/regression/api/v2/admin/users_spec.js#L10). Maybe a new section something like "Password reset" and can be based on this [acceptance test](https://github.com/TryGhost/Ghost/blob/2.25.0/core/test/acceptance/old/admin/users_spec.js#L306).

Let's keep this PR going once decided on the details of implementation. Thanks for your contribution! :tada:

2019-07-22 15:36 UTC, naz requested changes
Needs to adapt session deletion and take into account currently logged in user (their session should stay active) as discussed [here](https://github.com/TryGhost/Ghost/issues/10323#issuecomment-511350932)

2019-07-22 16:59 UTC, vikaspotluri123 commented
Definitely makes sense! This might need a bit of thought as to when and where we attach the session id 🤔

2019-10-27 17:19 UTC, closed without merging