Fix import overriding private setting
TryGhost/Ghost pull request #10882
Opened 2019-07-08 08:09 UTC by allouis

closes #10788 

- This removes the `is_private` setting from imports under *all* conditions.
- This outputs a "problem" when the import data's `is_private` settings differs from the current databases `is_private` setting.

2019-07-23 09:48 UTC, gargol commented
yo @allouis what's the status of this PR? Looks like the tests need fixing and it's gonna be ready to :rocket:

2019-07-23 09:51 UTC, allouis commented
Yo! Tests need fixing, but actually needs a lot more work, Zimo and John wanted some design changes, like moving this error to the top of the errors list, which will require a refactor. I can pick up some more dev work next week, but I can't see this being merged until Zimo is back - I could be wrong about that tho

2019-07-23 09:58 UTC, gargol commented
Hm. Can the task be split into couple parts maybe? 1st would get this change in, so people don't accidentally override the private setting and have a follow up with design improvement? But maybe it's a no-go with this warning being lost in the clutter of other ones?

2019-07-23 10:00 UTC, allouis commented
> But maybe it's a no-go with this warning being lost in the clutter of other ones?

I think that was John's main issue with it - let's see what he thinks, @JohnONolan any thoughts on the above discussion?

2019-07-24 03:08 UTC, JohnONolan commented
Agree with @gargol - we can polish up the warning design later, be good to get the rest in now 👍

2019-07-24 03:08 UTC, allouis commented
Will finish this Monday for a merge :relaxed:

2019-07-29 10:58 UTC, gargol commented
Just making sure the behavior implemented is expected one. There are 4 scenarios with different outcomes at the moment:
1. Import of `is_private: false` into the site with `is_private: false` - no change.
2. Import of `is_private: false` into the site with `is_private: true` - we keep the site private as intended BUT! if the import contains a `password` field from settings it gets overridden (this doesn't seem right). 
3. Import of `is_private: true` into the site with `is_private: true` - same behavior as pt.2
4. Import of `is_private: true` into the site with `is_private: false` - the site stays public + show the warning message

Think pts 2 and 3 should not be resetting the password (needs to be filtered out along with `is_private` flag when importing)

2019-07-29 11:00 UTC, naz requested changes

2019-07-29 11:00 UTC, gargol commented on core/server/data/importer/importers/data/settings.js
> +        if (oldIsPrivate === false && newIsPrivate === true) {
```suggestion
        if ((oldIsPrivate && newIsPrivate) && (!!oldIsPrivate.value === false && !!newIsPrivate.value === true)) {

```

The check should take into account that these are models being compared `.value` bit, and that they might not be present in the imported file and the `value` might also be a string in the incoming data :grimacing:

2019-07-29 12:10 UTC, gargol commented on core/server/data/importer/importers/data/settings.js
> +        if (oldIsPrivate === false && newIsPrivate === true) {
P.S. might be worth to get the new behavior covered a little with unit tests if not too much extra work

2019-08-05 04:56 UTC, allouis commented
@gargol This is good to go IMO :tada:

2019-08-05 10:21 UTC, naz approved these changes

2019-08-05 10:22 UTC, gargol commented
@allouis :ship: it

2019-08-06 08:15 UTC, merged