[anu]#11038 Fixed es-lint issues
TryGhost/Ghost pull request #11178
Opened 2019-10-01 05:06 UTC by anusreePrakash

- removed ghost/mocha/no-sibling-hooks

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test` and `yarn lint`)

More info can be found by clicking the "guidelines for contributing" link above.

2019-10-01 05:10 UTC, allouis requested changes

2019-10-01 05:10 UTC, allouis commented on core/test/acceptance/old/admin/themes_spec.js
> -        return ghost()
`mocha` uses the return value (if it's a promise) in `before`, `beforeEach` etc.. to know when the setup/teardown has completed. So remove of the `return` here is changing functionality. I think you'll want to either update these to `async` functions and `await` the operations, continue to `return` promises OR change it to `before(function (done) {` and call `done` when everything is setup!

2019-10-16 08:37 UTC, gargol commented on core/test/acceptance/old/admin/themes_spec.js
> +    describe('fafa', function () {
Not sure this is a good name for this describe group :grimacing:

2019-10-16 08:40 UTC, gargol commented
:wave:  @anusreePrakash let us know if you need help with these changes. I'd focus on only fixing the `no-sibling-hooks` rule for now and do any additional improvements to test suites as a separate PR (regarding changes like this onehttps://github.com/TryGhost/Ghost/pull/11178#discussion_r329880611)

2019-10-30 16:11 UTC, gargol commented
Happy to reopen whenever you have some time to finish the PR @anusreePrakash :wink:

2019-10-30 16:11 UTC, closed without merging