:bug: Fix issue - kg-bookmark tags available on RSS feed XML
TryGhost/Ghost pull request #11822
Opened 2020-05-18 13:43 UTC by pr3d

fixes #11705

This will replace the bookmark card with the html anchor element.
To do so, it

- greps the `href` attribute to get the url
- greps the text content of the element with the class `kg-bookmark-publisher` to get the site title
- finally replaces the element with the class `kg-bookmark-card` with the html anchor element

2020-06-09 12:01 UTC, kevinansfield requested changes
Hey @pr3d 👋 Thanks for looking at this! I've reviewed the code quickly and I think there are two things that need addressing:

1. The code currently assumes there is only one bookmark card in a post but there can in fact be many - we'll want to use cheerio to query for all bookmark cards and loop over and replace each one
2. The `<a>` that replaces each bookmark card should be wrapped in a `<p>` so that semantics and layout are maintained

2020-08-04 14:13 UTC, matthanley commented
ping @kevinansfield for review 😄

2020-11-05 17:01 UTC, devdreamsolution approved these changes

2021-02-02 17:53 UTC, closed without merging

2021-02-03 12:20 UTC, daniellockyer commented
Hey @pr3d! 👋🏻 Unfortunately your PR got automatically closed when we renamed branches yesterday because your fork seems to have been deleted. If you fancy reopening the PR again with a new fork, we'd be more than happy to take another look 🙂