Refactored the slack & unsplash settings
TryGhost/Ghost pull request #12050
Opened 2020-07-15 14:26 UTC by allouis

refs #10318 

- [x] moves the `slack.url` setting into `slack_url`
- [x] moves the `slack.username` setting into `slack_username`
- [x] moves the `unsplash.isActive` setting into `unsplash_is_active`
- [x] updates importer to skip `slack_url`
- [x] updates slack service to use new settings
- [ ] updates settings api to ignore old settings

2020-07-15 14:27 UTC, allouis commented
https://github.com/TryGhost/Ghost/pull/12050/commits/c414ff581c6f241dce5951d41f21f5c7ea6b999a & https://github.com/TryGhost/Ghost/pull/12050/commits/c414ff581c6f241dce5951d41f21f5c7ea6b999a contain the migrations :relaxed:

2020-07-15 14:34 UTC, daniellockyer requested changes

2020-07-15 14:34 UTC, daniellockyer commented on core/server/data/migrations/versions/3.26/02-refactor-slack-setting.js
> +        transation: true
typo :pencil2:

2020-07-15 14:34 UTC, daniellockyer commented on core/server/data/migrations/versions/3.26/03-refactor-unsplash-setting.js
> +        transation: true
typo :pencil2:

2020-07-15 14:38 UTC, allouis commented on core/server/data/migrations/versions/3.26/02-refactor-slack-setting.js
> +        transation: true
:grimacing:

2020-07-15 14:38 UTC, allouis commented on core/server/data/migrations/versions/3.26/03-refactor-unsplash-setting.js
> +        transation: true
:grimacing:

2020-07-15 14:45 UTC, ErisDS commented
This is missing handling for unsplash in the importer?

2020-11-05 17:01 UTC, devdreamsolution approved these changes

2020-11-05 17:54 UTC, allouis commented
Closing to keep repo clean, will keep the branch if we decide we need this again!

2020-11-05 17:54 UTC, closed without merging