Published Time and Modified Time was not populating for pages structured data
TryGhost/Ghost pull request #12081
Opened 2020-07-25 02:43 UTC by roshandash411

closes TryGhost#12059
Published Time and Modified Time were not populating for 'page' context because it is an extension of 'post' and hence there was no context 'page'. Fixed it by handling this scenario for published time and modified time

2020-07-25 13:33 UTC, adamhenson approved these changes

2020-07-27 16:05 UTC, ErisDS commented
Hey @roshandash411 thanks for the PR! 

Although this would work, it's not quite the correct fix IMO - I remember looking at this code recently and realising it wasn't consistent. Would love for someone to give this the proper ❤️  it needs, and I don't think it's a huge change.

If you take a look at the e.g. `author_image.js` you'll see there's a `getContextObject()` function that handles all this logic and returns the correct object to pull attributes from.

The reason for doing this instead of the fix in this PR is it's significantly more future proof - if we change anything to do with how pages are rendered in future, using the shared `getContextObject()` function everywhere will help to prevent things like this regressing (again).

2020-07-27 16:06 UTC, ErisDS requested changes
Hey @roshandash411 thanks for the PR! 

Although this would work, it's not quite the correct fix IMO - I remember looking at this code recently and realising it wasn't consistent. Would love for someone to give this the proper ❤️  it needs, and I don't think it's a huge change.

If you take a look at the e.g. `author_image.js` you'll see there's a `getContextObject()` function that handles all this logic and returns the correct object to pull attributes from.

The reason for doing this instead of the fix in this PR is it's significantly more future proof - if we change anything to do with how pages are rendered in future, using the shared `getContextObject()` function everywhere will help to prevent things like this regressing (again).

2020-07-27 23:53 UTC, roshandash411 commented
Yeah I get what you're saying. Sure, I'll work on it

2020-07-28 02:09 UTC, roshandash411 commented
@ErisDS I've created a new PR with the changes you told would make this future proof. This PR, https://github.com/TryGhost/Ghost/pull/12085 ,  should help fix the above issue, and probably also a few other missing fields 😅 due to fixing the getContextObject() function.

2020-07-28 02:09 UTC, closed without merging