Added new routes_hash setting
TryGhost/Ghost pull request #12171
Opened 2020-09-02 05:29 UTC by naz

refs #11999

The migration updates new `routes_hash` setting based on the rule of adding new settings [laid out here](https://github.com/TryGhost/Ghost/issues/12026#issuecomment-656238588). Theoretically the `flags` and `type` fields don't have to be set explicitly, but added them in an update based on the same reasoning as in [similar previous migration](https://github.com/TryGhost/Ghost/pull/12028#discussion_r452756111).

2020-09-03 05:02 UTC, rishabhgrg approved these changes

2020-09-03 07:04 UTC, daniellockyer approved these changes

2020-09-03 07:57 UTC, daniellockyer requested changes
We haven't released 3.32 yet so you can move them into that if we're expecting this to be OK to merge soon :slightly_smiling_face:

2020-09-03 08:19 UTC, daniellockyer approved these changes

2020-09-07 08:25 UTC, kevinansfield approved these changes

2020-09-07 09:54 UTC, merged