Collect member name
TryGhost/Ghost pull request #12191
Opened 2020-09-08 14:34 UTC by bourrel

https://github.com/TryGhost/Ghost/issues/12029

Add the ability to get member names from `data-member-forms`.

--------

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test` and `yarn lint`)

2020-09-21 13:58 UTC, matthanley commented
cc @rishabhgrg as similar may be required in Portal for backwards compat

2020-09-21 14:03 UTC, allouis requested changes
One comment - otherwise LGTM :tada:

2020-09-21 14:03 UTC, allouis commented on core/server/public/members.js
> +        var email_input = event.target.querySelector('input[data-members-email]');
We generally use camelCase rather than snake_case - would you be able to update? :relaxed:

2020-09-23 09:37 UTC, allouis commented
Hey @bourrel this looks awesome!! Thanks for you contribution! I've tested this locally and it's working :ok_hand:

There's just one thing I missed, would you be able to run `grunt uglify` which will update the minified version of this file, and commit that - after that i'll merge this to master and it'll be in our next release :tada:

2020-09-23 09:52 UTC, bourrel commented
Thanks, @allouis !

I've updated the uglified version, I hope this will be good for merging :)

2020-09-23 12:59 UTC, merged

2020-09-23 12:59 UTC, allouis commented
:woman_dancing: And done, thanks for your work!