Add tokens table
TryGhost/Ghost pull request #12209
Opened 2020-09-16 15:04 UTC by allouis

This is a table to store single use tokens for use in magic links, the
columns are as simple as possible at the moment and are designed as:

`id` - standard ObjectID like all of our tables
`token` - 128bit base64 encoded string
`data` - arbitrary data to store against the token
`created_at` - timestamp to allow for expiry to be implemented for tokens

2020-09-16 21:24 UTC, daniellockyer requested changes

2020-09-17 08:06 UTC, allouis commented on core/server/data/migrations/utils.js
> +                logging.warn(`Adding table: ${name}`);
Dun!

2020-09-17 08:06 UTC, allouis commented on core/server/data/migrations/utils.js
> +                logging.warn(`Dropping table: ${name}`);
And dun!

2020-09-17 08:14 UTC, rishabhgrg reviewed
Changes look good, just wondering if we should add any of the other standard columns like `created_by`, `updated_at`, `updated_by` here, mostly `created_by` and then hook it up with actions table which helps us keep internal track of who created a token etc for any checks later?  🤔

2020-09-17 09:03 UTC, kevinansfield commented
> Changes look good, just wondering if we should add any of the other standard columns like `created_by`, `updated_at`, `updated_by` here, mostly `created_by` and then hook it up with actions table which helps us keep internal track of who created a token etc for any checks later? 🤔

Is there anything in this table that would be updated after creation?

2020-09-17 09:05 UTC, kevinansfield approved these changes
Looks good 👍 If we have a `created_at` we should probably have a `created_by` too if these resources can be created by authenticated users rather than as a system side-effect.

2020-09-17 09:18 UTC, allouis commented
@kevinansfield 
> Is there anything in this table that would be updated after creation?

Nope! These are created, and then as soon as they are read for the first time, they will be deleted :relaxed:

> If we have a created_at we should probably have a created_by too if these resources can be created by authenticated users rather than as a system side-effect.

:+1: I'm gonna add that now!

2020-09-17 12:35 UTC, rishabhgrg approved these changes

2020-09-17 12:50 UTC, daniellockyer approved these changes

2020-09-17 15:08 UTC, merged