Settings default to fix
TryGhost/Ghost pull request #12265
Opened 2020-10-06 14:14 UTC by lunaticmonk

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test` and `yarn lint`)

Fixes https://github.com/TryGhost/Ghost/issues/12181

More info can be found by clicking the "guidelines for contributing" link above.

2020-10-07 04:32 UTC, lunaticmonk commented
@naz Please review.

2020-10-19 23:05 UTC, naz requested changes

2020-10-19 23:05 UTC, naz commented on core/server/models/settings.js
> +            type: ''
Does this default ever gets executed? If it's not used I think we could remove the `defaults` function completely?

2020-11-02 10:14 UTC, naz commented on core/server/data/schema/schema.js
> +            defaultTo: '',
Don't think there should be any default in this case at all. If it were to default to something it should at least be a value form `validations`. Removing `defaultTo: ''` parameter should be fine :+1:

2020-11-02 10:15 UTC, naz requested changes
The `defaultTo` value in schema should not be set to empty string :wink:

2020-11-03 10:36 UTC, lunaticmonk commented
@naz Pardon for being late. Full time job keeping busy 😄 Will do it in a day!

2020-11-03 23:27 UTC, naz commented
@lunaticmonk all good and no hurry :) Thanks for handling this!

2020-11-03 23:28 UTC, naz commented
@lunaticmonk all good and no hurry :) Thanks for handling this!
@daniellockyer would be good to have your :heavy_check_mark:  on this ;)

2020-11-04 10:22 UTC, daniellockyer approved these changes

2020-11-05 16:57 UTC, devdreamsolution approved these changes

2021-01-04 02:34 UTC, naz commented
This PR has landed in master as https://github.com/TryGhost/Ghost/commit/e756af65f2666926f1621cc50e4014dd74493959. Thanks for your contribution @lunaticmonk!

2021-01-04 02:34 UTC, closed without merging