Added members_product_events table
TryGhost/Ghost pull request #13236
Opened 2021-08-20 12:58 UTC by allouis

refs https://github.com/TryGhost/Team/issues/873

This table is to track events related to members be given or having
removed access to products. It will allow us to provide start dates for
access for complimentary members, as well as being able to track access
to products over time, either for individual members or for aggregates.

2021-08-20 13:07 UTC, matthanley requested changes
Is the expectation that we get multiple events for a product change (one removal, one addition)?

2021-08-20 13:07 UTC, matthanley commented on core/server/data/schema/schema.js
> +                isIn: [['add', 'remove']]
On the [actions table](https://github.com/TryGhost/Ghost/blob/50354633487558e4e4520d10a173182b979018cf/core/server/data/schema/schema.js#L548) the actions are past tense afaict - these should be consistent

2021-08-20 13:10 UTC, allouis commented
> Is the expectation that we get multiple events for a product change (one removal, one addition)?

Yeah that's right

2021-08-23 09:33 UTC, rishabhgrg approved these changes

2021-08-23 09:59 UTC, daniellockyer approved these changes

2021-08-23 14:28 UTC, matthanley approved these changes

2021-08-23 14:29 UTC, merged