:bug: Fixed AssetHelper not working with svg
TryGhost/Ghost pull request #13978
Opened 2022-01-15 20:23 UTC by torstenzander

closes #13971

This fixes an issue with svg sprites using the # to select an icon, when a ?v=hash is rendered the svg images is not shown. The bugfix removes ?v=hash param for svg files with an #.

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

More info can be found by clicking the "guidelines for contributing" link above.

2022-01-19 15:08 UTC, ErisDS commented
Hey @torstenzander thanks for the PR :) 

I don't think this is the fix that you want. The `?v=` query param is for cache busting, so this change would mean any svg with a # would get stuck in cache indefinitely.

The correct fix would be to insert the `?v=` param before the #, and maintain both.

Also, this bug would affect absolutely any path with a #, although it currently only really makes sense to use with an SVG, there's no need to limit the solution if implemented this way  🙂

2022-01-19 15:11 UTC, ErisDS requested changes
Hey @torstenzander thanks for the PR :)

I don't think this is the fix that you want. The ?v= query param is for cache busting, so this change would mean any svg with a # would get stuck in cache indefinitely.

The correct fix would be to insert the ?v= param before the #, and maintain both.

Also, this bug would affect absolutely any path with a #, although it currently only really makes sense to use with an SVG, there's no need to limit the solution if implemented this way 🙂

2022-01-19 15:11 UTC, ErisDS commented on test/unit/frontend/meta/asset-url.test.js
> +        testUrl.should.equal('/assets/myfile.svg#arrow-up');
```
testUrl.should.equal(`/assets/myfile.svg?v=${config.get('assetHash')}#arrow-up`);
```

I'd expect the test to look like this :)

2022-02-06 12:32 UTC, torstenzander commented
I am not sure if I have to do anything, my tests cover everything I added even though the coverage report looks different.

2022-02-07 15:06 UTC, ErisDS approved these changes
Hey @torstenzander no you don't need to do anything. Thanks for your work :)

2022-02-07 15:07 UTC, merged