Added format option to `img-url` helper
TryGhost/Ghost pull request #14962
Opened 2022-06-03 11:36 UTC by SimonBackx

no issue

- Added support for resizing images from Unsplash using the `img-url` helper
- Added support for setting the format of images, with a new  `format` option:

E.g. to convert an image to webp (only works in combination with size for now, except for Unsplash where you can use it without size):
```
{{img_url @site.cover_image size="s" format="webp"}}
```

This can help improve the performance of a theme, by serving assets in <picture> elements with webp and fallback image formats.

2022-06-24 21:38 UTC, markstos commented
Since this is targeted at Unsplash, there is a alternative that would be less work for theme developers and also Ghost. Instead of asking Unsplash for a specific format, Unsplash in turn uses the Imgix API and it supports `auto=format`.

This allows the potential that the Unsplash API might return the AVIF format if the browser supports it, which could be even smaller than `webp` while having higher visual "appeal". Here's what the Imgix API docs say:

> If [auto=format](https://docs.imgix.com/apis/rendering/auto/auto#format) is set and the browser does not support the AVIF format, we'll first fallback to WebP if it is supported. If WebP is not supported, imgix will fall back to the source image type.

https://docs.imgix.com/apis/rendering/format/fm#avi

And here's where the Unsplash API docs mention support for `auto=format`:

https://unsplash.com/documentation#dynamically-resizable-images

Related: there's an open "Idea" for Ghost to improve support for the AVIF format. Improving the Unsplash integration could a first step.

2022-07-15 13:42 UTC, markstos commented
Sounds good, @SimonBackx

2022-08-01 10:24 UTC, ErisDS requested changes
Very minor thing, but the change to middleware/handle-image-sizes.js reduces the coverage down from 100%. Could you please add a test to fix this?

Otherwise, this change looks great 👍

2022-08-01 11:25 UTC, ErisDS approved these changes

2022-08-01 12:45 UTC, merged