Replaced Promise.each() with .all() in models/base/bookshelf
TryGhost/Ghost pull request #15509
Opened 2022-09-30 10:40 UTC by CarolBarno

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change, explained below
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution! 

Also, if you'd be interested in writing code like this for us more regularly, we're hiring:
https://careers.ghost.org/product-engineer-node-js

2022-10-02 08:40 UTC, ErisDS commented on ghost/core/core/server/models/base/bookshelf.js
> -                return Promise.each(targets.models, function (target, index) {
This change doesn't look right to me. Promise.all takes an array of iterables

2022-10-02 08:41 UTC, ErisDS requested changes

2022-10-02 08:41 UTC, ErisDS commented on ghost/core/core/server/models/base/bookshelf.js
> -                return Promise.each(targets.models, function (target, index) {
This change doesn't look right to me. Promise.all takes an array of iterables

2022-10-13 13:40 UTC, ErisDS approved these changes

2022-10-13 14:24 UTC, merged

2022-10-13 14:26 UTC, ErisDS commented
Hi @CarolBarno thanks again for this PR and for taking the time to update it. Sorry for the delay (I got a little swamped with PRs) but it has now been merged 🎉 and will appear in the next release of Ghost - usually Fridays.

I'm not sure if you found this through hacktoberfest, but I've added the accepted label to this PR to make sure it counts. 

There are many more places where Promise.map is used, would be very grateful for more PRs like this (and faster at merging I _promise_!) ❤️

2022-10-13 15:09 UTC, CarolBarno commented
Hi @ErisDS , thanks for your response and let me look at similar places that require replacing.