Added e2e test for page.tag.detached event
TryGhost/Ghost pull request #15651
Opened 2022-10-18 16:22 UTC by Dark-Knight11

refs: #15537

This adds an e2e test and test snapshot for the `page.tag.detached` webhook so we can prevent regressions and bugs in the future

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change, explained below
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

Also, if you'd be interested in writing code like this for us more regularly, we're hiring:
https://careers.ghost.org

2022-10-19 03:28 UTC, naz commented on ghost/core/test/e2e-webhooks/pages.test.js
> +const buildPageSnapshotWithTiersAndTags = ({
Would it make sense to reuse the `buildPageSnapshotWithTiers` method here?

2022-10-19 03:33 UTC, naz commented on ghost/core/test/e2e-webhooks/pages.test.js
> +    name: anyString,
The tag's name, slug, visibility etc. are not changing between test runs? If they are not, would be best to have snapshot capture them as is - no need to include non-dynamic properties in the snapshot matcher object 👍

2022-10-19 03:35 UTC, naz requested changes
Hey-hey @Dark-Knight11 👋  These are great changes are I think we are 90% there. I've left couple of comments around areas that need improvement. Feel free to reach out if you need more guidance and thanks for the contribution!

2022-10-19 14:58 UTC, Dark-Knight11 commented
> Hey-hey @Dark-Knight11 👋 These are great changes are I think we are 90% there. I've left couple of comments around areas that need improvement. Feel free to reach out if you need more guidance and thanks for the contribution!

Hi, I have made the requested changes kindly look into it and lmk if anymore changes are needed from my side.
Thanks!

2022-10-20 04:39 UTC, naz commented
The snapshots seem to be outdated on and are failing now. Can you please re-record them again @Dark-Knight11 🙏

2022-10-24 06:57 UTC, naz approved these changes
Great work on these changes @Dark-Knight11! Looking forward for more contributions 😊

2022-10-30 14:59 UTC, merged

2022-10-30 15:02 UTC, ErisDS commented
Hey @Dark-Knight11 thanks again for your contributions! This has been merged and the `hacktoberfest-accepted` label added to make sure it counts.

Please keep them coming 🙏 we have so much we want to achieve beyond hacktoberfest 😬