remove hardcoded values from Portal
TryGhost/Ghost pull request #15661
Opened 2022-10-19 13:52 UTC by cathysarisky

- [X] There's a clear use-case for this code change, explained below
- [X] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`) 

Hi!  First pull request, please forgive me for any rookie mistakes.  I'm learning!

Portal currently has a Globals.js file that should spell out all the colors in use in Portal, which should make it easy to customize the portal colors to match the chosen theme.  Unfortunately, there are a bunch of hardcoded values.  This PR attempts to deal with those.  Perhaps longer-term, portal can take a set of arguments for light vs dark mode, but getting all the values that need to change in a custom Portal build into one file seemed like the place to start!

Most changes will be absolutely invisible.  In a few cases, a hardcoded value was close but not identical to one of the existing color variables, so I chose the closest existing option.

Why isn't the third box checked?  I've got something wrong with my development environment - can't get yarn test:all to run.  I did build it and confirm that it looks fine, no weird color changes or console errors.

2022-10-25 05:42 UTC, peterzimon requested changes
Hey @cathysarisky,

Thanks for your PR. Most of your changes are valid however there are a couple of places where hard coded colors are intentional.

1. In general we would not encourage people to change the color of drop shadows in Portal esp. that the same value would/could be used elsewhere. Let's keep the drop shadow colors hard coded to their original values.
2. I left a couple of comments and explanation in specific places which should also remain hard coded.

Thanks again, I'll review and test your PR again once these changes are applied.

Cheers,
Zimo

2022-10-25 05:42 UTC, peterzimon commented on ghost/portal/src/components/TriggerButton.styles.js
> +        color: var(--white)
Missing `;` at EOL

2022-10-25 05:42 UTC, peterzimon commented on ghost/portal/src/components/Frame.styles.js
> -    background: linear-gradient(45deg, rgba(255,255,255,1) 0%, rgba(249,249,250,1) 100%);
This is used in Ghost Admin only, the colors here are not supposed to be changed. Let's keep it hardcoded

2022-10-25 05:42 UTC, peterzimon commented on ghost/portal/src/components/Frame.styles.js
> +    background: var(--white);
This logo is marketing material which should be the same everywhere. These values should remain hardcoded.

2022-10-25 05:42 UTC, peterzimon commented on ghost/portal/src/components/Frame.styles.js
> +    color: var(--grey1);
This logo is marketing material which should be the same everywhere. These values should remain hardcoded.

2022-10-25 05:42 UTC, peterzimon commented on ghost/portal/src/components/Frame.styles.js
> +    color: var(--grey0);
This logo is marketing material which should be the same everywhere. These values should remain hardcoded.

2022-10-25 05:42 UTC, peterzimon commented on ghost/portal/src/components/Frame.styles.js
> +    color: var(--grey0);
This logo is marketing material which should be the same everywhere. These values should remain hardcoded.

2022-10-25 05:42 UTC, peterzimon commented on ghost/portal/src/components/TriggerButton.styles.js
> +        box-shadow: rgba(var(--blackrgb), 0.24) 0px 8px 16px -2px;
The trigger button shadows and outlines are chosen to work in most situations regardless of the background color. They are not supposed to be changed, let's keep them hardcoded.

2022-10-25 15:58 UTC, cathysarisky commented on ghost/portal/src/components/TriggerButton.styles.js
> +        color: var(--white)
good catch *blush*

2022-10-25 16:25 UTC, cathysarisky reviewed
Changes made, thanks @peterzimon !

2022-10-31 20:14 UTC, ErisDS commented
Hey @cathysarisky thanks for the updates. @peterzimon is off for a few days and not able to redo the review, but I've added `hacktoberfest-accepted` here in the meantime.

2022-10-31 22:25 UTC, cathysarisky commented
> Hey @cathysarisky thanks for the updates. @peterzimon is off for a few days and not able to redo the review, but I've added `hacktoberfest-accepted` here in the meantime.

It's all good!  :)  Thanks.

2022-11-09 10:24 UTC, peterzimon requested changes
Hey @cathysarisky 
Thanks for your changes, as I was testing your code I found two more minor issues. Could you please take a look at those and I'll retest them? 
Thank you, Zimo

2022-11-09 10:24 UTC, peterzimon commented on ghost/portal/src/components/common/ProductsSection.js
> +            background: var(--grey13);
There's a subtle but very important difference between the `#F3F3F3` and `var(--grey13)` which makes the contrast worse when using `var(--grey13)`. Let's keep the hard coded value.

2022-11-09 10:24 UTC, peterzimon commented on ghost/portal/src/components/common/ProductsSection.js
> +            box-shadow: 0px 1px 3px rgba(var(--blackrgb), 0.08);*/
This piece of code is commented, let's just delete it.

2023-01-24 12:20 UTC, peterzimon approved these changes

2023-01-24 12:23 UTC, merged