Update Ukrainian language translations
TryGhost/Ghost pull request #20443
Opened 2024-06-22 12:30 UTC by Vadimkin

This pull request adds Ukrainian translations for previously missing keys in the localization file. I also changed informal pronoun "твоєї" to formal "вашої" for better consistency and formality.

2024-06-27 20:24 UTC, akabuda050 requested changes

2024-06-27 20:24 UTC, akabuda050 commented on ghost/i18n/locales/uk/comments.json
> +    "{{amount}} characters left": "Залишилось {{amount}} символів",
```suggestion
    "{{amount}} characters left": "Залишилось {{amount}} символ(ів)",
```

2024-06-27 20:24 UTC, akabuda050 commented on ghost/i18n/locales/uk/comments.json
> +    "{{amount}} comments": "{{amount}} коментарів",
```suggestion
    "{{amount}} comments": "{{amount}} коментар(ів)",
```

2024-06-27 20:24 UTC, akabuda050 commented on ghost/i18n/locales/uk/comments.json
> +    "{{amount}} comments": "{{amount}} коментарів",
і т.д.

2024-06-27 20:33 UTC, akabuda050 commented on ghost/i18n/locales/uk/comments.json
> +    "{{amount}} characters left": "Залишилось {{amount}} символів",
хммм. можливо не треба й заборочуватися. бо варіанти такі як `Залишилось(вся) 1/2  символ(ів)`  буде занадто :)

2024-06-27 20:33 UTC, akabuda050 approved these changes

2024-10-14 14:53 UTC, ErisDS commented
Hey @Vadimkin, thanks for your contributions 🙏  I believe the changes here have been covered by https://github.com/TryGhost/Ghost/pull/20709, but if I've missed anything please feel free to open a new changeset ☺️

2024-10-14 14:53 UTC, closed without merging