Added new Czech translations
TryGhost/Ghost pull request #20941
Opened 2024-09-08 14:17 UTC by tombarys

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

We appreciate your contribution!

2024-09-09 12:42 UTC, tombarys commented
> Hey @tombarys 👋 Thank you for working on this. Could you please remove any sorting you've applied to these files? The language files are automatically generated and need to maintain the original ordering for the system to work correctly and tests to pass.

Oh sorry!

2024-09-09 13:02 UTC, tombarys commented
Not sure what I am doing wrong. I have manually replicated the structure of /en locale JSONs in committed files.

2024-09-16 09:57 UTC, kevinansfield commented on ghost/i18n/locales/cs/portal.json
> +    "Thank you for your support": "Děkujeme za vaši podporu",
I think this may be the issue, lines 132 and 133 have been swapped

2024-09-16 15:45 UTC, sagzy requested changes
Hey @tombarys, thanks for the updates. There are two remaining changes that are making the CI fail, I've highlighted them in my review. In general, when looking at the code changes [here](https://github.com/TryGhost/Ghost/pull/20941/files), the English part (keys) should not change, only the Czech part (values)

2024-09-16 15:45 UTC, sagzy commented on ghost/i18n/locales/cs/comments.json
> +    "Report this comment": "Nahlásit tento komentář",
Lines 53 and 54 have been swapped

2024-09-16 15:45 UTC, sagzy commented on ghost/i18n/locales/cs/portal.json
> +    "Sorry, that didn't work.": "Omlouváme se, to nefungovalo.",
`didn’t` has been changed to `didn't` (note the `’` versus `'`)

2024-09-17 17:15 UTC, sagzy approved these changes
Looking good now, thanks for the follow-up changes. Merging :)

2024-09-17 17:15 UTC, merged

2024-09-29 08:58 UTC, tombarys commented
Hi, thanks for the assistance and patience with me. I was just wondering when the translation will be in production. It seems that it does not work yet. See my newsletter sent in Czech:

![CleanShot 2024-09-29 at 10 54 21@2x](https://github.com/user-attachments/assets/157facc2-abdd-45a6-bb8e-fd8cab84c102)

Thanks!

2024-10-01 10:47 UTC, sagzy commented
> Hi, thanks for the assistance and patience with me. I was just wondering when the translation will be in production. It seems that it does not work yet. See my newsletter sent in Czech:
> 
> ![CleanShot 2024-09-29 at 10 54 21@2x](https://private-user-images.githubusercontent.com/5729352/371840080-157facc2-abdd-45a6-bb8e-fd8cab84c102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3Nzk3ODQsIm5iZiI6MTcyNzc3OTQ4NCwicGF0aCI6Ii81NzI5MzUyLzM3MTg0MDA4MC0xNTdmYWNjMi1hYmRkLTQ1YTYtYmI4ZS1mZDhjYWI4NGMxMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDFUMTA0NDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQ4NzEwNTdmNzExZjVkOTk5YWFlOWIzMjdmMjZlNTk2YTVhZjlkZDhjOGM1MjAxM2Q5MmVjOTkxYWUxMWM0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4UxAKmQvZZazLkYXuYyr1ZotdYUhtLVg_VgLoJ1SA_Y)
> 
> Thanks!

@tombarys 👋 

Your translations should be live as you update your site to the latest Ghost version.

This particular part of the product - the paywall card - is currently not covered by translations. An improvement to make in the future :)