Complete pt translation
TryGhost/Ghost pull request #21023
Opened 2024-09-17 12:48 UTC by chicodurden21

Portuguese version updated, portuguese native here. Everything was translated based on the formal you.

2024-09-17 17:06 UTC, sagzy requested changes
Thanks for the PR, great work! I left two comments. Additionally, the CI is failing due to a syntax error in `ghost/i18n/locales/pt/portal.json`

2024-09-17 17:06 UTC, sagzy commented on ghost/i18n/locales/pt/portal.json
> +    "(save {{highestYearlyDiscount}}%)": "Poupe {{highestYearlyDiscount}}%",
Missing parenthesis `()` and no capital letter on P

2024-09-17 17:06 UTC, sagzy commented on ghost/i18n/locales/pt/portal.json
> +    "jamie@example.com": "janedoe@themoneygame.pt",
Could we leave the default here? Jamie Larson, and jamie@example.com

2024-09-17 17:08 UTC, sagzy commented on ghost/i18n/locales/pt/portal.json
> +    "To continue to stay up to date, subscribe to {{publication}} below.": "Para continuar atualizado, subscreva o {{publication}} aqui."
Syntax error: missing `,` at the end of the line

2024-09-17 18:58 UTC, chicodurden21 commented
done, I think you can merge it now. let me know if I need to change something else.

2024-09-17 20:11 UTC, sagzy approved these changes
Thanks for the updates! Merging :)

2024-09-17 20:11 UTC, merged

2024-09-23 14:15 UTC, chicodurden21 commented
![the money game](https://github.com/user-attachments/assets/097506d3-3eae-4550-b013-8a195770ac9a)

Good afternoon, 

looks like the code hasn´t been updated.

Cheers

2024-09-24 08:23 UTC, sagzy commented
> ![the money game](https://private-user-images.githubusercontent.com/179515701/369914978-097506d3-3eae-4550-b013-8a195770ac9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjYzMDQsIm5iZiI6MTcyNzE2NjAwNCwicGF0aCI6Ii8xNzk1MTU3MDEvMzY5OTE0OTc4LTA5NzUwNmQzLTNlYWUtNDU1MC1iMDEzLThhMTk1NzcwYWM5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwODIwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTc0YmQ3MDkyZDhjNDYxYjc1YzEyODQ2MWNhYjc2NTkzNmYzM2QwYTM4NDFkODdlYzNlZWQwNmM5MDFmNWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.60bL2GnBlu_1LWhh8LWdIcLEyHk50G_YkqI247My-lI)
> 
> Good afternoon,
> 
> looks like the code hasn´t been updated.
> 
> Cheers

Hey @chicodurden21! :) The translations of this PR have been released in [Ghost v5.94.2](https://github.com/TryGhost/Ghost/releases/tag/v5.94.2).

Portal translations are still in beta and need to be enabled in Settings -> Labs -> Portal translation ([docs](https://ghost.org/docs/faq/translation/)). Is that enabled on your site?

2024-09-27 14:07 UTC, chicodurden21 commented
I´ve enabled the portal translations in the settings, however the words are still shown in English. 

By the way, how do I update to the latest ghost version?

2024-10-01 09:04 UTC, sagzy commented
> I´ve enabled the portal translations in the settings, however the words are still shown in English.
> 
> By the way, how do I update to the latest ghost version?

@chicodurden21 👋 

If you're a Ghost (Pro) customer, your site is already updated automatically to the latest version. If you're a self-hoster, here are the [docs](https://ghost.org/docs/update/) on how to update Ghost to the latest version, using Ghost CLI

2024-10-01 10:09 UTC, chicodurden21 commented
there´s something wrong here then, because the sign in and subscribe button are still being shown in english. I am gonna contact the support. Thanks for the help anyway.