feat(i18n): add zh-Hant translation
TryGhost/Ghost pull request #21140
Opened 2024-09-26 17:20 UTC by imgarylai

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change, explained below
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

2024-09-26 19:03 UTC, cathysarisky requested changes
Hello!  Thank you for submitting these translations!
I'm happy to see that you were able to submit the missing portal strings and the ones needed to make search translated.
I'm helping out by taking a quick look at translations, with some help from AI.  I left a few comments where I thought that maybe the translation needed another look.  Please feel welcome and encouraged to indicate that any of my questions are irrelevant by marking them as resolved or by leaving a response.
When you've had a chance to make any needed changes (or left a comment that none of my concerns require changes), please let me know so that I can change my review to approved.

2024-10-06 07:58 UTC, dlackty reviewed
Hi, native zh-Hant speaker here :) I added few comments and I can help create a commit or new PR too if @imgarylai is busy.

Thanks @imgarylai & @cathysarisky !

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "(save {{highestYearlyDiscount}}%)": "省下 {{highestYearlyDiscount}}%",
Maybe we should keep `（）`？

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "Enter your email address": "你的 email",
Maybe `輸入你的 Email`？

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "Enter your name": "你的名字",
Same, maybe `輸入你的名字`

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "Invalid email address": "email 有誤",
Maybe `不合法的 Email 地址` is better.

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "Jamie Larson": "王小明",
Yes, I can confirm that. Actually there's a [wikipedia page](https://zh.wikipedia.org/zh-tw/%E7%8E%8B%E5%B0%8F%E6%98%8E) for this name as placeholder.

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "Something went wrong, please try again later.": "伺服器錯誤，請重試。",
Maybe we should add "later" in translation: `伺服器錯誤，請稍後重試。`

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "There was an error processing your payment. Please try again.": "付款失敗，麻煩你再試一次",
Maybe `付款發生錯誤，請你再試一次。`? Just want to consistently use 請 as please

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "To continue to stay up to date, subscribe to {{publication}} below.": "繼續訂閱 {{publication}} 以獲得最新消息",
Yes, Cathy is right. I would advice `訂閱 {{publication}} 以持續獲得最新消息`

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "Unsubscribed from all emails.": "取消訂閱所有電子報",
Yes, this should be `未訂閱任何電子報` instead.

2024-10-06 07:58 UTC, dlackty commented on ghost/i18n/locales/zh-Hant/portal.json
> +    "Verification link sent, check your inbox": "確認信件已經寄出，請查收",
May we use `驗證連結已寄出，請確認你的信箱` instead?

2024-10-12 23:55 UTC, imgarylai commented
Hey @cathysarisky @dlackty, thank you for those suggestion. I was on vacation last week. I will address these comments and publish another revision. 

Thanks

2024-10-13 13:07 UTC, dlackty approved these changes

2024-10-13 13:49 UTC, cathysarisky reviewed
Thanks for the additions! 

I notice that Github thinks you added some changes to casper, probably on accident?

2024-10-13 22:37 UTC, imgarylai commented
There was some issue on git submodule sync. I syncced it and the problem has been resolved. Thanks!

2024-10-13 23:07 UTC, cathysarisky approved these changes

2024-10-16 08:26 UTC, merged