Update search.json
TryGhost/Ghost pull request #21233
Opened 2024-10-05 08:09 UTC by fochoa8

Proper translation of search.json, all checked with Spanish translation. "Tags" translates to "Etiquetas", the short form to say "Labels" in Spanish as well, in both instances, the application of the word is fine given that Ghost is a blog.

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change, explained below
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

2024-10-06 02:44 UTC, cathysarisky requested changes
Not recommended for merge until all spelling errors and unexpected punctuation are corrected.

2024-10-07 06:29 UTC, fochoa8 reviewed
Done.

2024-10-07 11:41 UTC, cathysarisky commented
> Done.

No, there remains another spelling error/typo.

2024-10-07 12:07 UTC, fochoa8 commented
> > Done.
> 
> No, there remains another spelling error/typo.

![image](https://github.com/user-attachments/assets/8a0d1fc6-7e94-4eef-8987-e67831a9f420)

![image](https://github.com/user-attachments/assets/22ed6046-af9c-4318-be96-0c72583a2fce)

![image](https://github.com/user-attachments/assets/60216d6a-d4d6-4112-9561-ad543b932869)

![image](https://github.com/user-attachments/assets/0c7b4434-3176-4075-8705-0476c5ca4823)

![image](https://github.com/user-attachments/assets/d98d69cb-ff90-4cc4-a387-56f00a423846)

![image](https://github.com/user-attachments/assets/cbdbfcb7-e389-41f5-9ae0-91711d5396a8)

Thanks,
Fernando Ochoa Olivares.

2024-10-07 12:13 UTC, cathysarisky approved these changes

2024-10-07 12:30 UTC, fochoa8 reviewed
Past tense fixed in "No matches found" proper translation is "No se ecnontraron resultados", as well proper translation of "Matches" equals "Resultados" in Spanish.

![image](https://github.com/user-attachments/assets/9057edaf-9b61-42c0-a7b2-e29610f4dc4e)

2024-10-14 12:12 UTC, cathysarisky requested changes

2024-10-14 12:12 UTC, cathysarisky commented on ghost/i18n/locales/es/search.json
> +    "Show more results": "Muestra más resultados",
Could you link a major Spanish-language website that uses Muestra for a show more results link?  I'm seeing Mostrar.

2024-10-14 12:12 UTC, cathysarisky commented on ghost/i18n/locales/es/search.json
> +    "Search posts, tags and authors": "Buscar publicaciones, etiquetas y Autores",
What grammar rule has Autores being capitalized?  Thanks!

2024-10-14 17:09 UTC, 9larsons commented
Closing as duplicate of https://github.com/TryGhost/Ghost/pull/21246.

2024-10-14 17:09 UTC, closed without merging