(drafty) 🌐 First draft of RTL support for Portal
TryGhost/Ghost pull request #21238
Opened 2024-10-06 17:46 UTC by cathysarisky

A draft of RTL support for Portal.

2024-10-07 12:23 UTC, sagzy reviewed
Hey @cathysarisky, really cool! Left two comments

2024-10-07 12:23 UTC, sagzy commented on apps/portal/src/components/Frame.styles.js
> +.mr2 { margin-inline-endt: 8px; }
Typo: `margin-inline-endt:` (extra `t`)

2024-10-07 12:26 UTC, cathysarisky commented on apps/portal/src/components/Frame.styles.js
> +.mr2 { margin-inline-endt: 8px; }
embarrassing! Thank you!

2024-10-07 12:29 UTC, cathysarisky commented on apps/portal/src/components/Frame.styles.js
> +    right: 24px;
agreed, that's an error.  (Although I don't actually see an impact of that change, it might be important at some screen size.)  Fixing...

2024-10-16 14:58 UTC, sagzy approved these changes
LGTM 👍 

Pending design review from @peterzimon

2024-10-23 09:36 UTC, dvdwinden requested changes
Hi @cathysarisky, 

Thank you for submitting your PR! Much appreciated.

I reviewed it from a design point-of-view, and the CSS looks great. I did find two small issues when testing it.

First: when going to **Email Preferences**, the question mark for _Not receiving emails?_ sits in the wrong place. I believe this is a common issue when implementing RTL support, and I wonder if there's anything we can do to mitigate it?

<img width="543" alt="image" src="https://github.com/user-attachments/assets/006e6d04-b0f8-425b-8eed-64902d308498">


Second: in the main **Account** modal, below the headline, there's a sentence about your current membership. On the second line of that sentence, the period is in the wrong place — similar to the question mark mentioned above. 

<img width="534" alt="image" src="https://github.com/user-attachments/assets/3ceeefd6-ad39-4504-a35c-700195bad30a">

Could you have a look at these?

2024-10-23 11:05 UTC, cathysarisky commented
Thanks @dvdwinden for the review!  I think the period and question mark's positions not actually a problem.  They are in the "right place" -- it's just that your text isn't RTL (because it is English), so it looks weird.  

I'm not sure which language you have set.  (Maybe you forgot to turn on the portal translations in settings > labs?)  If you switch to Arabic, you should see the 'Not receiving emails?' rendered as: 
"Not receiving emails?": "لم تستلم رسالة بريدية؟",
Happily, the punctuation is wrapped in the string, so we get the backward question mark in the right place without portal doing extra work.
![image](https://github.com/user-attachments/assets/88ba6269-dae2-4b44-bd3c-d0eff5ad0b98)

I switched over to Urdu for the other string, since translations are more complete there:
![image](https://github.com/user-attachments/assets/9d22bdc8-1a5c-4b5c-9cb5-c299831f2cfe)

2024-10-23 11:11 UTC, dvdwinden approved these changes
@cathysarisky Excellent, thank you for clarifying — this looks great!

2024-10-25 09:19 UTC, merged