Added Turkish local for portal
TryGhost/Ghost pull request #21314
Opened 2024-10-16 06:12 UTC by xyxforyou

I jast want to change my theme to Turkish language

2024-10-16 11:20 UTC, cathysarisky commented on ghost/i18n/locales/context.json
> +    "Search posts, tags and authors": "Gönderileri, etiketleri ve yazarları arayın",
translations don't belong in context.json. Please revert this change
```suggestion
    "Search posts, tags and authors": "",
```

2024-10-16 11:28 UTC, cathysarisky requested changes
Hello xyzforyou!  Thanks for this effort.

You've accidentally committed a folder called 'en copy', and you have folders called tr and TR.   

What we need is a folder named 'tr', containing the five files (comments, ghost, portal, search, signup-form).   We already have Turkish translations in the system, so you should start from there and look for what needs to be updated, rather than starting from nothing.

You may find it easier to start a new pull request that has the intended changes (created by editing the existing files in locales/pr), rather than trying to fix the issues with this one.  Either way, hit the 'request review' button or tag me when you've got things fixed and I'll be back to check it over, ok?

2024-10-25 07:42 UTC, allouis commented
@xyxforyou Do you intend to continue work on this PR?

2024-10-28 03:44 UTC, allouis commented
Closing due to inactivity

2024-10-28 03:44 UTC, closed without merging