Complete Korean.
TryGhost/Ghost pull request #21577
Opened 2024-11-09 06:58 UTC by hellosunghyun

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change, explained below
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

2024-11-11 12:56 UTC, cathysarisky requested changes
Please see my comment on selecting a name for Jamie Larson, rather than transliterating.  Everything else look good to an AI inspection.

2024-11-11 12:56 UTC, cathysarisky commented on ghost/i18n/locales/ko/portal.json
> +    "Jamie Larson": "제이미 라슨",
instead of transliterating Jamie Larson, could you please pick a common Korean name?  Something that would be recognized as a name placeholder?

2024-11-11 13:06 UTC, hellosunghyun commented
Complete!

2024-11-11 13:13 UTC, cathysarisky approved these changes

2024-11-12 08:06 UTC, ronaldlangeveld commented
안녕하세요 성현 @hellosunghyun  :) 
Thank you very for your ongoing translations! 🙏🏻 You may find a few more strings to translate—if you come across any that need work in 한국어, don’t hesitate to reach out! 🎉

2024-11-12 08:24 UTC, merged