i18n: add missing Arabic translation file
TryGhost/Ghost pull request #21651
Opened 2024-11-19 00:57 UTC by KHAWARIZMIX

- Translated all keys in the following language JSON files to Arabic: Ghost, Portal, Search, Signup-	Form, and Comments.
- Ensured consistency and accuracy for improved user experience 
- Verified language integration and formatting for consistency

This commit provides the Arabic translation for all relevant UI components in Ghost CMS, filling a previously missing language option.

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change, explained below
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

2024-11-19 13:15 UTC, cathysarisky commented on ghost/i18n/locales/ar/comments.json
> +    "Jamie Larson": "جيمي لارسون",
the original translation for "Jamie Larson" is better, as it is intended to be a generic name, not a literal transliteration.

2024-11-19 13:38 UTC, cathysarisky commented
Hello, and thank you for this submission.  Although your post says you're adding a missing file, these appear to all be changes to existing translations.  @mostafty and @almrx and @ksaart , I would be grateful if you would review these translations and reach consensus on what the best wording is.

2024-11-19 17:54 UTC, cathysarisky commented
Let's see if @KHAWARIZMIX responds.  If K's unresponsive, you could certainly put in a new PR and this one could be closed without merging.  But perhaps K will respond (and we should give them a couple days as a courtesy) and you can collaborate. :)

2024-11-19 20:03 UTC, KHAWARIZMIX commented
Hello, thank you for your kind response!
To be honest, I had already pushed my translation to the repository a few days ago, as I noticed there wasn’t a complete Arabic translation available at the time. However, since it was my first time contributing, I forgot to create a pull request until today.

I deeply appreciate the efforts of all contributors, especially the Arabic translators. I didn’t attempt to merge my translation because I thought it was better than anyone else’s work, but simply because I wasn’t aware that others were already contributing.

I’m not here to compete or challenge others. My goal is to offer my help to the community that I admire and want to support.

2024-11-20 17:28 UTC, cathysarisky commented
@KHAWARIZMIX , thanks for the reply and for explaining what happened!  If you and the other Arabic speakers can work together to agree on a 'best' set of translations, that'd be great.  I don't have anything to add here. :)

2024-12-12 14:59 UTC, cathysarisky commented
Hello - checking in here!  What can I do to help move these translations forward?

2024-12-13 10:14 UTC, KHAWARIZMIX commented
Hello, I hope the conflicts have been fixed as expected!

2025-01-22 16:36 UTC, cathysarisky requested changes

2025-01-22 16:36 UTC, cathysarisky commented on ghost/i18n/locales/ar/comments.json
> +    "{{amount}} characters left": "الحروف المتبقية: {{amount}}",
You have lost the { and } around this file.  These are required for the i18next to understand your work.  Please correct.

2025-01-22 16:37 UTC, cathysarisky commented
Bumping this - @mostafty and @almrx and @KSAART , if one of you has time to provide feedback on the updated version of these translations, I would appreciate it!

2025-01-29 15:35 UTC, cathysarisky commented on ghost/i18n/locales/ar/comments.json
> +    "{{amount}} characters left": "الحروف المتبقية: {{amount}}",
Good catch, @coderabbitai! The opening and closing braces are important in all json files that contain translation strings, in ghost/i18n/locales

2025-01-29 15:35 UTC, cathysarisky commented on ghost/i18n/locales/ar/portal.json
> +    "+1 (123) 456-7890": "",
@coderabbitai, you can specifically ignore the phone number field localization.

2025-05-06 09:05 UTC, closed without merging