Update portal.json
TryGhost/Ghost pull request #21671
Opened 2024-11-20 20:50 UTC by echobilisim3421

The person who did the translation included their name and surname, which was a mistake. This has been corrected.

2024-11-21 15:10 UTC, cathysarisky commented
Please see previous comments about this change here: https://github.com/TryGhost/Ghost/pull/21440

2024-11-21 15:11 UTC, cathysarisky requested changes

2024-11-21 15:11 UTC, cathysarisky commented on ghost/i18n/locales/tr/portal.json
> +    "jamie@example.com": "kullanıcıadı@example.com",
See https://github.com/TryGhost/Ghost/pull/21440

2024-11-21 18:32 UTC, cathysarisky commented on ghost/i18n/locales/tr/portal.json
> +    "jamie@example.com": "kullanıcıadı@example.com",
See https://github.com/TryGhost/Ghost/pull/21440#discussion_r1852660737

2024-11-22 23:03 UTC, closed without merging

2024-11-22 23:03 UTC, 9larsons commented
Please stop submitting duplicates.