Update ghost.json
TryGhost/Ghost pull request #21826
Opened 2024-12-08 21:08 UTC by alexrodba

Corregides formes incorrectes de:
* Direcció -> Adreça
* Subscribir-te -> Subscriure't (Ambdues són barbarismes).
* Si us plau -> Si-us-plau

Corregit typo de "seguro" a "segur".

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ x] There's a clear use-case for this code change, explained below
- [x ] Commit message has a short title & references relevant issues
- [x ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

2024-12-10 13:48 UTC, cathysarisky commented
Hi @Zagur !  Do you have a moment to review these Catalan refinements?

2024-12-10 13:48 UTC, cathysarisky commented
Hi @Zagur ! Do you have a moment to review these Catalan refinements?

2024-12-10 23:21 UTC, alexrodba reviewed
Fixed two lines

2025-01-29 15:50 UTC, cathysarisky commented
@coderabbitai full review

2025-01-29 16:09 UTC, cathysarisky commented
@Hana-Gausfain and @alexrodba : Last question from me before merge time: "si us plau" vs "si-us-plau" ? Googling seems to favor unhyphenated, but I see that this PR changes it to hyphenated. (Hana-Gausfain's previous PR did not.) I'm not a Catalan speaker (and it's OK to ignore the recommendations from the AI bunny here), but just wanted to confirm that hyphenated is correct, rather than spending the next couple years adding and removing hyphens! 🤣

2025-01-29 16:26 UTC, Zagur commented
> @Hana-Gausfain and @alexrodba : Last question from me before merge time: "si us plau" vs "si-us-plau" ? Googling seems to favor unhyphenated, but I see that this PR changes it to hyphenated. (Hana-Gausfain's previous PR did not.) I'm not a Catalan speaker (and it's OK to ignore the recommendations from the AI bunny here), but just wanted to confirm that hyphenated is correct, rather than spending the next couple years adding and removing hyphens! 🤣

The hyphenated form is incorrect. The correct spelling in Catalan is "Si us plau." I'm not sure if the use of hyphens was a typo or a misunderstanding, but in Catalan, it is written without them.

2025-01-30 20:14 UTC, cathysarisky requested changes
@alexrodba , I can't remove the hyphens for you, but I've left you suggestions you can commit to do so. :)  I think this is ready to go otherwise?

2025-01-30 20:14 UTC, cathysarisky commented on ghost/i18n/locales/ca/ghost.json
> +    "Please confirm your email address with this link:": "Si-us-plau, confirma la teva adreça de correu electrònic amb aquest enllaç:",
```suggestion
    "Please confirm your email address with this link:": "Si us plau, confirma la teva adreça de correu electrònic amb aquest enllaç:",
```

2025-01-30 20:14 UTC, cathysarisky commented on ghost/i18n/locales/ca/ghost.json
> +    "You're one tap away from subscribing to {{siteTitle}} — please confirm your email address with this link:": "Estàs a un sol pas de subscriure't a {{siteTitle}} — si-us-plau, confirma la teva adr
```suggestion
    "You're one tap away from subscribing to {{siteTitle}} — please confirm your email address with this link:": "Estàs a un sol pas de subscriure't a {{siteTitle}} — si us plau, confirma la teva adreça de correu electrònic amb aquest enllaç:",
```

2025-02-10 16:09 UTC, merged