Update newsletter.json
TryGhost/Ghost pull request #21828
Opened 2024-12-08 21:20 UTC by alexrodba

Added missing translations

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [ ] There's a clear use-case for this code change, explained below
- [ ] Commit message has a short title & references relevant issues
- [ ] The build will pass (run `yarn test:all` and `yarn lint`)

We appreciate your contribution!

2024-12-10 13:37 UTC, cathysarisky requested changes

2024-12-10 13:37 UTC, cathysarisky commented on ghost/i18n/locales/ca/newsletter.json
> +    "Your free trial ends on {date}, at which time you will be charged the regular price. You can always cancel before then.": "El teu periode de prova s'acaba el {date}. A partir d'aleshores, se't c
Please check the spelling. Should it be període ?

2024-12-10 13:48 UTC, cathysarisky commented
Hi @Zagur ! Do you have a moment to review these Catalan refinements?

2024-12-10 23:15 UTC, alexrodba reviewed
Updated file

2024-12-10 23:17 UTC, alexrodba reviewed
Fixed typo

2025-01-29 15:39 UTC, cathysarisky commented
@coderabbitai , please review

2025-01-29 15:41 UTC, cathysarisky commented on ghost/i18n/locales/ca/newsletter.json
> +    "Your free trial ends on {date}, at which time you will be charged the regular price. You can always cancel before then.": "El teu periode de prova s'acaba el {date}. A partir d'aleshores, se't c
Nudge - I see a thumbs up for this, but not a fix. :)

2025-02-05 06:42 UTC, merged