🌐 Added and corrected strings in the Norwegian (no) i18n locale files.
TryGhost/Ghost pull request #21904
Opened 2024-12-17 20:17 UTC by knutid

no issue
- added missing strings
- corrected one string

2025-01-22 16:57 UTC, cathysarisky commented
Really important context missing from your PR main message and buried in a comment (https://github.com/TryGhost/Ghost/pull/21904/commits/95e98fc616a5265f553de7b69e36b057c79cd5ea) :  You're changing the locale code from no to nb.  

**The proposed change is going to break translations for all sites that currently use the 'no' locale.**  

Additionally, if the change is going to be made, the supported_locales variable of i18n.js must be updated also.  (Otherwise it won't work for EITHER locale code.)

It sounds like a switch to 'nb' is the right thing to do, but it needs to be done with more care than the current PR.  sym-linking might be appropriate, but I'm not sure if the current build step for translation files can actually handle it.

2025-01-22 16:57 UTC, cathysarisky requested changes
Really important context missing from your PR main message and buried in a comment (https://github.com/TryGhost/Ghost/commit/95e98fc616a5265f553de7b69e36b057c79cd5ea) : You're changing the locale code from no to nb.

The proposed change is going to break translations for all sites that currently use the 'no' locale.

Additionally, if the change is going to be made, the supported_locales variable of i18n.js must be updated also. (Otherwise it won't work for EITHER locale code.)

It sounds like a switch to 'nb' is the right thing to do, but it needs to be done with more care than the current PR. sym-linking might be appropriate, but I'm not sure if the current build step for translation files can actually handle it.

2025-01-23 02:21 UTC, cmraible commented
@cathysarisky nice catch! I haven't tried this so we'd need to test, but it looks like i18next supports a [fallbackLng parameter](https://www.i18next.com/principles/fallback#language-fallback) which we might be able to use here. If I'm reading the docs right, basically we'd set `nb` as the fallback for `no`, then remove `no`.

2025-01-28 14:51 UTC, cathysarisky commented
Hey @xqus , would you like to review these proposed translations?

2025-01-29 07:26 UTC, xqus reviewed
Translations looks good. 👍 
One minor comment, but the original suggestion also works.

2025-01-29 07:26 UTC, xqus commented on ghost/i18n/locales/nb/comments.json
> +    "Once deleted, this comment can’t be recovered.": "Når slettet, kan ikke kommentaren gjenopprettes.",
Maybe change to:  `Når denne kommentaren er slettet kan den ikke gjennopprettes.`.
This is a more natural way to say it in Norwegian.

2025-01-29 12:49 UTC, cathysarisky commented
There are two things going on here.  One: Fixes to language.  Those will be mergeable fairly quickly.  Two: The change to locale.  That's going to require someone to work through making fallback strings work so that we don't break anything for existing users.  (Alternative: write a database migration that switches anyone set to 'no' to 'nb' ?)  I'm not going to get a chance to do that for a while -- overbooked with paying work.  @knutid, if adding that is within your skill set, please have at it!  Otherwise, you're waiting for someone to pick it up and figure it out.  So... it might be best to split the locale change out from the translation adjustments.  That'll get the translation adjustments in sooner, and decouples the issue of what the locale name is from the changes wanted in it.

2025-02-03 20:48 UTC, knutid commented
My javascript-foo is totally missing. So, I'll look into splitting, @cathysarisky.

2025-03-01 21:46 UTC, cathysarisky commented
Since this PR has a review already, we could go ahead and merge it if  the no->nb change were removed.  Or one of you could review #22194 , and we could merge that one.  As a non-Norwegian speaker, I will get out of the way and let the native speakers decide which way to proceed.

2025-03-05 22:11 UTC, knutid commented
Hi, @cathysarisky.

Close this PR, #21904, and move forward with PR #22194 and my comments, tnx!

2025-03-10 13:50 UTC, 9larsons commented
Closing, thanks!

2025-03-10 13:50 UTC, closed without merging