🌐 Added and improved Dutch translations
TryGhost/Ghost pull request #21959
Opened 2024-12-31 16:12 UTC by VirtualRoy

Hey there,

I completed some missing translation keys and found a few translation errors I adjusted. I'm a Dutch native, but feel free to double-check the edits.

Thanks for building such awesome software for us to enjoy! ✨

2025-01-22 17:09 UTC, cathysarisky requested changes
Thank you for this contribution!

2025-01-22 17:09 UTC, cathysarisky commented on ghost/i18n/locales/nl/comments.json
> +    "Replied to": "Antwoord op",
I notice that you have the same translation for 'reply to' and 'replied to'.  Is this an error?

2025-01-23 16:35 UTC, VirtualRoy commented on ghost/i18n/locales/nl/comments.json
> +    "Replied to": "Antwoord op",
@cathysarisky While both are technically correct, I do recognize that it depends on the context. The context in context.json seems to be empty for this key. I've updated the translation for "Replied to" to "Geantwoord op" to better reflect the past tense.

2025-01-28 14:44 UTC, cathysarisky approved these changes
lgtm

2025-01-28 17:15 UTC, merged