Remove default template dependency on client side CSS
TryGhost/Ghost pull request #8217
Opened 2017-03-23 04:01 UTC by TienSFU25

See Issue #8126

Adds these files under /shared
- normalizer.css
- error.css
- extracted.css (for subscribers.css and private.css)

Also makes these files available as public static content

2017-03-23 10:45 UTC, aileen requested changes
`private.hbs` and `subscribe.hbs` are requesting a css file that doesn't get served. This would need to be corrected, to make it work.

`error.hbs` is looking good to me.

2017-03-23 10:45 UTC, AileenCGN commented on core/server/apps/private-blogging/lib/views/private.hbs
> +        <link rel="stylesheet" href="/extracted.css"/>
`extracted.css` is not served.

2017-03-23 10:45 UTC, AileenCGN commented on core/server/apps/subscribers/lib/views/subscribe.hbs
> +    <link rel="stylesheet" href="/extracted.css"/>
Same as above, `extracted.css` doesn't exist.

2017-03-23 10:45 UTC, AileenCGN commented on core/server/blog/app.js
> +    blogApp.use(serveSharedFile('subscribers.css', 'text/css', utils.ONE_HOUR_S));
Instead of using three different css files, you could simplify it and just serve all the styles from one file instead.

2017-03-23 21:18 UTC, TienSFU25 commented on core/server/blog/app.js
> +    blogApp.use(serveSharedFile('subscribers.css', 'text/css', utils.ONE_HOUR_S));
okay. what should this file be called? `shared.css` sounds too generic.

2017-03-23 21:19 UTC, TienSFU25 commented
Also do I need to add unit tests for adding the shared file?

2017-03-24 09:57 UTC, AileenCGN commented on core/server/blog/app.js
> +    blogApp.use(serveSharedFile('subscribers.css', 'text/css', utils.ONE_HOUR_S));
I would probably just go for `ghost.css`, the way it was before?

2017-03-25 06:47 UTC, TienSFU25 commented
why is the core/client stuff in here? I don't understand

2017-03-28 14:16 UTC, kevinansfield commented
@TienSFU25 the `core/client` changes are there because you staged the `core/client` submodule before committing.

To remove them now that you've committed you would need to go through the following steps:
1. `cd core/client`
2. find the ref that `master` currently points to (see image below)
3. `git checkout {{ref}}` (in this case `git checkout a8e58bf`)
4. `cd ../../`
5. `git add core/client`
6. `git commit -m "reset core/client submodule"` (or if you want to change the existing commit you could do `git commit --amend --no-edit`)

<img width="592" alt="screen shot 2017-03-28 at 15 10 40" src="https://cloud.githubusercontent.com/assets/415/24409885/6f4e6166-13c9-11e7-9642-a1238c44bcc2.png">

2017-04-05 15:09 UTC, ErisDS commented
This was merged in #8234, thanks @TienSFU25 for your hard work!

I know you've had trouble getting in touch with us to ask questions - we are active in slack but most of us are in UK/EUR timezones. The #core-dev channel is specifically for asking contributing related questions & we've worked on overhauling our tools and docs to start making it easier. Let us know if there's anything else we can do.

2017-04-05 15:09 UTC, closed without merging