https image urls if accessed over SSL
TryGhost/Ghost pull request #8373
Opened 2017-04-22 23:25 UTC by sovietspaceship

Tentative fix for #8372. I'm not familiar with this codebase so I don't know the rationale behind the current code nor whether this change would be enough, but hopefully will point to the right direction.

2017-04-24 06:26 UTC, kirrg001 requested changes
Thanks for your PR!

Could you please add a test case to proof your case is not working?

Probably in `core/test/unit/utils/url_spec.js`.

2017-04-24 16:48 UTC, sovietspaceship commented
Our blog had optional https but http by default, so it was configured with an http base url. The https version of the rss feed was returning http links for images as the current code only checks the image path for https, ignoring that the actual connection may be https. This PR fixes it.

2017-05-10 09:54 UTC, kirrg001 commented on core/server/utils/url.js
> +            secure = data.image.secure || secure;
Sorry for late review!

I just double checked this line of code. `data.image.secure` is never a case. We expect `image` to be the url path. If you remove the whole line, it should work as expected.
Thanks for adding the test 👍

2017-05-10 14:48 UTC, sovietspaceship commented on core/server/utils/url.js
> +            secure = data.image.secure || secure;
You're right, data.image is a string.
Done.

2017-05-15 11:08 UTC, kirrg001 approved these changes
👍 Thank you!

2017-05-15 11:09 UTC, merged