🐛 Run primary tag through visibility filter
TryGhost/Ghost pull request #8924
Opened 2017-08-19 17:18 UTC by ErisDS

Ensures that the visibility rules are applied to a primary tag

closes #8920

- Added a new, efficient first method
- Applies visibility the same way as filter in tag/foreach helpers

2017-08-19 17:18 UTC, ErisDS commented on core/test/unit/utils/url_spec.js
> +var should = require('should'), /* jshint ignore:line */
unrelated cleanup

2017-08-22 10:10 UTC, kevinansfield requested changes

2017-08-22 10:10 UTC, kevinansfield commented on core/server/models/post.js
> +            attrs.primary_tag = visibility.first(attrs.tags, ['public']);
I think `visibility.first` is returning `undefined` when no tag matches which is resulting in no `primary_tag` property being added causing the tests to fail.

I'm not sure if `visibility.first` should be returning `null` or if we need a `|| null` conditional here.

2017-08-24 08:09 UTC, ErisDS commented on core/server/models/post.js
> +            attrs.primary_tag = visibility.first(attrs.tags, ['public']);
An `|| null` here would be correct IMO, have pushed an update

2017-08-24 08:13 UTC, kevinansfield commented on core/server/models/post.js
> +            attrs.primary_tag = visibility.first(attrs.tags, ['public']);
👍 will merge once it's green so we have something for today's release 😁

2017-08-24 09:39 UTC, ErisDS commented
Been working through primary tags next & previous and just realised this behaviour needs a little rethink. Will try to get it sorted asap.

2017-08-24 11:42 UTC, ErisDS commented
Closing this in favour of #8934

2017-08-24 11:42 UTC, closed without merging