use excerpt in rss if no meta_description is set
TryGhost/Ghost pull request #9219
Opened 2017-11-06 11:57 UTC by rambii

issue #9210

- added fallback for post excerpt
- added test

2017-11-06 12:16 UTC, rambii commented
How is the build error related to the commit?

2017-11-06 12:50 UTC, AileenCGN commented
@rambii was just a timeout issue. I restarted the test. It's passing now 🎉

2017-11-06 14:25 UTC, rambii commented
@AileenCGN thanks for the feedback :)

2017-11-06 14:56 UTC, kevinansfield requested changes

2017-11-06 14:56 UTC, kevinansfield commented on core/server/data/xml/rss/index.js
> +                description: post.meta_description || post.custom_excerpt || downsize(htmlContent.html(), {words: 50}),
@rambii thanks for looking at this! One quick change that is required... the `custom_excerpt` should be used if available, then fall back to the others:

`description: post.custom_excerpt || post.meta_description || downsize(htmlContent.html(), {words: 50}),`

2017-11-06 15:32 UTC, rambii commented
@kevinansfield I updated it accordingly (y)

2017-11-07 05:31 UTC, AileenCGN commented
@kevinansfield This looks good to me now! Can I merge?

2017-11-07 10:14 UTC, kevinansfield approved these changes

2017-11-07 10:16 UTC, merged