Fixes - #9263 - Changed the symbol to use :)
TryGhost/Ghost pull request #9313
Opened 2017-12-10 17:47 UTC by Abijeet

Fixes #9263 

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `npm test`)

2017-12-11 04:56 UTC, aileen requested changes
Hey @Abijeet 

Thanks for the PR. I don't know, if you've tested this with a Slack webhook, but changing the `:simple-smile:` to `:)` didn't seem to work.

Maybe we just rename it to `:smile:`, which seems to work fine with Slack.

2017-12-11 04:56 UTC, AileenCGN commented on core/server/services/slack.js
> +        message: 'Heya! This is a test notification from your Ghost blog :). Seems to work fine!'
Tested with `:)` and this doesn't get rendered as emoji in Slack. I suggest, we change it to `:smile:` which - apparently - will work for both, Slack (I tested it and it works) and Discord.

2017-12-11 04:57 UTC, AileenCGN commented on core/server/services/slack.js
> +        message: 'Heya! This is a test notification from your Ghost blog :). Seems to work fine!'
![image](https://user-images.githubusercontent.com/8037602/33816287-70bc3dcc-de6a-11e7-8887-37627ed13e42.png)

See here ^ first message with `:)` and second with `:smile:`.

2017-12-11 18:09 UTC, Abijeet commented
@AileenCGN - Thanks for doing the bulk of the work for me. That was sloppy. I tried to test it, but got an error because I was copying a space from my slack web-hook URL to the slack integration URL in the admin settings. This was causing Ghost to complain about invalid URL. 

I was initially unable to understand why this was happening, but figured out when I went back this time.

I've now gone ahead and opened a PR to **fix** the above as well - https://github.com/TryGhost/Ghost-Admin/pull/925 . Please merge it if you think it's needed.

Adding an image this time,

![9263-test-case](https://user-images.githubusercontent.com/1685517/33846300-4920d5c2-decc-11e7-896c-19261225968a.png)

2017-12-15 04:16 UTC, aileen approved these changes

2017-12-15 04:19 UTC, merged