[WIP] Added demo post
TryGhost/Ghost pull request #9747
Opened 2018-07-23 13:22 UTC by kirrg001

no issue

[ci skip]

- add new migration for 1.25 to insert the draft demo post
- tested on sqlite3 + mysql
- add the new demo post to our fixtures to ensure a new blog get's the demo post as well
- ensure demo post is never inserted twice

2018-07-23 17:52 UTC, kirrg001 commented on core/server/data/schema/fixtures/fixtures.json
> +                    "author_id": "5951f5fca366002ebd5dbef7"
Did.

2018-07-24 10:12 UTC, kevinansfield requested changes
Aside from the demo post slug and improved skip message everything else here looks 👍 Tested on sqlite and it worked well.

2018-07-24 10:12 UTC, kevinansfield commented on core/server/data/schema/fixtures/fixtures.json
> +                    "slug": "koenig-demo-post",
As discussed we should change this to `v2-demo-post` to lower the likelihood of collisions with existing posts even further.

2018-07-24 10:12 UTC, kevinansfield commented on core/server/data/migrations/versions/1.25/2-demo-post.js
> +const message3 = 'Skip: Adding demo post.';
It would be nice to change this to mention why it was skipped. "Skipped adding demo post - slug already in use"

2018-07-24 12:34 UTC, kevinansfield approved these changes

2018-07-24 12:34 UTC, kevinansfield commented
@kirrg001 yes, sorry, missed the notifications 🙈

2018-07-24 12:37 UTC, merged