Removed change frequency and priority from sitemap
TryGhost/Ghost pull request #9771
Opened 2018-08-08 21:56 UTC by damanm24

Removed change freq and priority from sitemap and tests

closes #9765
Google says that change frequency and priority are not important when search engines crawl through pages. Therefore, these two properties are unimportant and removed from Ghost. [Reference](https://www.seroundtable.com/google-priority-change-frequency-xml-sitemap-20273.html)

2018-08-09 18:45 UTC, damanm24 commented
That's odd on my local machine all the tests pass, I am unsure as to why they fail when run through Travis CI. Any ideas?

2018-08-09 19:04 UTC, freezboltz commented
Same thing happen to me
 I think some extra test is going on here

2018-08-09 19:08 UTC, kirrg001 commented
Tests sometimes fail randomly in Travis.

2018-09-10 12:34 UTC, kirrg001 commented on core/server/data/xml/sitemap/base-generator.js
> -    getPriorityForDatum() {
There are some more occurrences of `getPriorityForDatum` if you do search e.g. in tag-generator.

2018-09-10 12:36 UTC, kirrg001 requested changes
Thanks for the PR. Looks good to me. Just left one comment - there are some more functions to cleanup.

2018-09-17 09:30 UTC, kirrg001 commented
@damanm24 ping :)

2018-09-24 11:11 UTC, kirrg001 commented
I would like to take over this PR and finish it up later :) Let me know if you are around today and if you would like to fix the comments on your own.

2018-09-24 16:39 UTC, damanm24 commented
> 
> 
> I would like to take over this PR and finish it up later :) Let me know if you are around today and if you would like to fix the comments on your own.

Yes please take over the PR. I don't have the time to get to it. Thanks.

2018-09-24 17:06 UTC, kirrg001 approved these changes
Updated the PR 👍

2018-09-24 17:16 UTC, merged